### ISSUE TITLE
Overpass API change?

### ISSUE THREAD

**Issue by bikeoid** [maxerickson/osm_ms_buildings#1]
For some reason, I now get an error on fetch.py from the Overpass server.   Running the command in a browser yields some syntax errors and I had to change line 11 from
 
 ```
   (._;>);
  to 
  (._;>;);
```

  It had worked earlier, so I assume that something changed on the server end.  It did work after the change.

**Comment by maxerickson** [comment]
Seems there must have been. There have been lots of changes to the parser:

https://github.com/drolbr/Overpass-API/commits/38092640e457cc02fed5b8b0d16ed38e43490e1b/src/overpass_api/frontend/tokenizer_utils.cc

In any case, I fixed the script.
